version: "3.8"

services:
  front-end:
    container_name: JamesTipTest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
